export const SET_ANNOUNCEMENTS = 'SET_ANNOUNCEMENTS'
export const SET_LOADING_ANNOUNCEMENTS = 'SET_LOADING_ANNOUNCEMENTS'
export const SET_ANNOUNCEMENT_DETAIL = 'SET_ANNOUNCEMENT_DETAIL'
export const SET_LOADING_ANNOUNCEMENT_DETAIL = 'SET_LOADING_ANNOUNCEMENT_DETAIL'
