export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN'
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
export const SET_LOADING_LOGIN = 'SET_LOADING_LOGIN'
export const SET_LOADING_REGISTER = 'SET_LOADING_REGISTER'
