export const SET_REPORTS_LIST = 'SET_REPORTS_LIST'
export const SET_LOADING_REPORTS = 'SET_LOADING_REPORTS'
export const SET_DETAIL_REPORT = 'SET_DETAIL_REPORT'
export const SET_LOADING_DETAIL = 'SET_LOADING_DETAIL'
