export const SET_REPORTS = "REPORT/SET_REPORTS";
export const SET_DETAIL_REPORT = "REPORT/SET_DETAIL_REPORT";
export const EDIT_REPORT = "REPORT/EDIT_REPORT";
export const SET_LOADING_REPORTS = "LOADING/SET_LOADING";
export const SET_LOADING_REPORTS_CATEGORY = "LOADING/SET_LOADING";
export const SET_LOADING_DETAIL = "LOADING/SET_LOADING";
export const SET_LOADING_PATCH = "LOADING/SET_LOADING";
export const SET_ERROR = "ERROR/SET_ERROR";
